### ISSUE TITLE
Plants don't grow

### ISSUE THREAD

**Issue by SpitefulFox** [CyanideX/Infernal-Skies#13]
Plants don't appear to actually grow or progress at all without the use of bonemeal.  Saplings stay saplings forever.  The wormwood plant grows to full with bonemeal and then never browns out.

**Comment by Helakarma** [comment]
Have the same problem in overworld. Placed torches next to them, then they grew (had to cheat them in)

**Comment by SpitefulFox** [comment]
I have that glowy flowerpot next to my wormwood plant and it's sort of in range of my saplings.  If it's a light issue, not sure how I'm supposed to grow anything without any other source of light.

**Comment by CyanideX** [comment]
Looking into it. It grows fine in the nether but not the overworld (I think it takes 8 times longer to grow).

**Comment by valsnoisytoys** [comment]
Yeah, I had the same issue in the overworld, thought maybe I was just being impatient. :P

**Comment by CyanideX** [comment]
Fixed. Wait for the update (0.1.5.0) coming tomorrow.
