### ISSUE TITLE
0.1.5.0 Water barrels don't collect rain in overworld

### ISSUE THREAD

**Issue by valsnoisytoys** [CyanideX/Infernal-Skies#15]
I had 6 water barrels under rain for about 10 minutes and none of them filled, not even partially.

**Comment by CyanideX** [comment]
It's working on my end in the plains biome. Make sure it's not in the desert.

![Rain](http://i.imgur.com/wliITp0.png)

Report issues again if you're still having this problem.

**Comment by valsnoisytoys** [comment]
![2015-06-22_23 56 53](https://cloud.githubusercontent.com/assets/12927065/8299792/74eed6e0-193a-11e5-90ab-398bae24135c.png)

Still having it.

**Comment by CyanideX** [comment]
Try spawning in a barrel and see if that one fills.

**Comment by valsnoisytoys** [comment]
Spawned in ones still don't fill with water, alas. (In fact, I also noticed the spawned in one didn't stack with my hand made ones).

**Comment by CyanideX** [comment]
Are you able to put fluids inside?

**Comment by valsnoisytoys** [comment]
Yes, (Tried water bucket)

**Comment by CyanideX** [comment]
Ok, so water is visible in the barrel when placing it in manually? Can you
create a new world and try it with rain?

**Comment by valsnoisytoys** [comment]
Yep and you can take the water out of the barrel. I'll create a local world and see what happens.

**Comment by valsnoisytoys** [comment]
Ok a local world, using the same files I uploaded to the server, works fine. So is there something else beside the config/mod (minus the nonserver mods)/world folders I'm supposed to update when updating on the server side?

mods I removed from the server mod folder are:
Custom main menu
Hardcore map reset
Launch GUI
Resource loader
Mousetweaks

**Comment by CyanideX** [comment]
I honestly have no idea... I'll look into this in the morning.
