### ISSUE TITLE
Can't Make Hellfire Furnace

### ISSUE THREAD

**Issue by Vifury** [CyanideX/Infernal-Skies#16]
In the Nether, your island is netherrack. The netherrack is chisel 2 which won't allow you to make the Hellfire Furnace unless you chisel it back to normal netherrack. You can't make a chisel 2 chisel unless you get iron/diamond/obsidian. Could you make it so you can use chisel 2 netherrack to make the Hellfire Furnace?

**Comment by CyanideX** [comment]
No. If you can't make it, that means you're not supposed to. When you are able to make it with netherrack, that is the appropriate time.
