### ISSUE TITLE
Map is still glitched.

### ISSUE THREAD

**Issue by milasawi** [CyanideX/Infernal-Skies#17]
Is the modpack supossed to have a specific map?
Because i always get random generated ones.

**Comment by Vifury** [comment]
Yes, you start on an island where your in a box with blazes and such around. When I played multiplayer, I had to run the game once then change the map.

**Comment by CyanideX** [comment]
*It's not glitched*, you need to download the correct map and place it in your server directory (make sure the world folder is named "world").

Don't post non-issues here. Clearly there are thousands of people playing it without an issue so it isn't a problem with the map.

If you're looking for help setting up the server files, please turn to the [forums](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mod-packs/2093133-infernal-skies-hqm-map-modpack-wip-1-7-10-only). I'm sure people would be able to assist you there.
