### ISSUE TITLE
0.1.5.0 table sifter can't be broken by hand

### ISSUE THREAD

**Issue by valsnoisytoys** [CyanideX/Infernal-Skies#20]
I can't break table sifter by hand, have to use a pick. Shouldn't it be hand / axe? Has no stone its construction (overworld).  Note: I didn't have an axe yet test if it breaks with that.

**Comment by CyanideX** [comment]
Made note of this on the [subsistence repo](https://github.com/CyanideX/Subsistence/issues/106).
