### ISSUE TITLE
0.1.5.0 Light in the Nether easily(ish) gotten via glowstone blocks

### ISSUE THREAD

**Issue by valsnoisytoys** [CyanideX/Infernal-Skies#21]
The glowstone in the nether can be turned into easy light once you make a stone saw and make nooks - 32 per glowstone block.

**Comment by CyanideX** [comment]
I saw that when I loaded your map and was impressed that Goreae managed to figure that one out. I'm not opposed to the light if you can figure it out. Perhaps I will make it more challenging by removing the stone recipes. ;)
