### ISSUE TITLE
0.1.5.0 Blazes and Pigmen spawning in brighter light levels

### ISSUE THREAD

**Issue by valsnoisytoys** [CyanideX/Infernal-Skies#23]
Are blazes and pigmen supposed to be spawning in 8+ light levels? Makes the farms a problem with them  spawning all the time regardless of light.

**Comment by CyanideX** [comment]
Issue made on the [Subsistence repo](https://github.com/CyanideX/Subsistence/issues/108).

**Comment by CyanideX** [comment]
Pigmen should always spawn but I will report he blaze issue on VikeStep's Sprinkles repo.
