### ISSUE TITLE
0.1.5.0 Stone compost bin / barrel look burnable

### ISSUE THREAD

**Issue by valsnoisytoys** [CyanideX/Infernal-Skies#24]
They both say burn time 300 or something like that in the tool tip. Probably shouldn't be burnable (can't check if they really burn, don't have a furnace  yet).

**Comment by CyanideX** [comment]
That is fine although it should be fixed. If someone wants to waste a stone barrel by using it as fuel... well, that's their choice. :stuck_out_tongue:
