### ISSUE TITLE
Stuck on mod load loop

### ISSUE THREAD

**Issue by MoritzT** [CyanideX/Infernal-Skies#46]
When I start the game I get asked to install the missing mods (IC2 etc) once I downloaded and added them I restart the game. Unfortunately the same setup process pops up and I have to go through it again and again. It never recognises the mods :-(

Also when I uploaded the mods to the server, the server wouldn't start due to mods being duplicates.
Removing the 4 mods again and it worked fine, but then I get a client/server mod missmatch.

Tested today with 0.1.5.1 via Curse Launcher

**Comment by CyanideX** [comment]
It will never recognize the mods. The warning is there as a reminder in case you skipped the steps. Once all of the mods have been added you can proceed.

As for your mod mismatch, that's on your end. Delete and re-add all the server-side mods OR [download the server pack](https://github.com/CyanideX/InfernalSkies/tree/master/server) from this repo.
