### ISSUE TITLE
Nether player back at starting area

### ISSUE THREAD

**Issue by Tzian** [CyanideX/Infernal-Skies#51]
My partner and I had been playing fine over LAN for a few sessions, upon loading up the pack on our next session he was in the starting area (pre choosing a path) instead of his nether base.  It appeared to have lost his player.dat.

Don't know if that is something that is MC or pack related but thought would let you know it happened.

**Comment by CyanideX** [comment]
If your player data disappeared, that would be an issue on your end.

Did you friend set his spawn point via the spawn totem?

**Comment by Tzian** [comment]
Yeah he had set his spawn, we had had various sessions with no problem just that one session he logged in and was back at the start area.

Nay mind, we restarted and so far so good :D
