### ISSUE TITLE
Hand Sieve using material but not producing

### ISSUE THREAD

**Issue by FunshineX** [CyanideX/Infernal-Skies#9]
Is it intended to use dirt in the hand sieve?  I put a stack in the UI, then held down right click.  The dirt was consumed but no items were produced

How far into the quest line is "Completed" so I know where to stop even trying to play?

**Comment by FunshineX** [comment]
Nevermind apparently I'm supposed to use Loamy dirt..any chance at NEI integration for the sifted products?  That's a key feature Ex-Nihilo has that Subsistence is missing

**Comment by CyanideX** [comment]
No plans on NEI integration. The point of the mod within Infernal Skies is difficulty and immersion; not magical helpful GUIs. :stuck_out_tongue_winking_eye:
